name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:

jobs:
  trailhead-stats:
    name: Trailhead Stats
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Trailhead stats
        id: trailhead-stats
        uses: nabondance/Trailhead-Stats@main
        with:
          trailhead-username: nabondance
          display-type: 'card'
          display-file: 'README.md'
          filte-format: 'html'
          card-path: './'
