name: Update Trailhead Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch:
    inputs:
      trailhead-username:
        description: Username on Trailhead
        required: true
        type: string
        default: 'nabondance'
      display-type:
        description: 'Type of display: text|card|output'
        required: false
        type: string
        default: 'html'
      display-file:
        description: File to update to display
        required: false
        type: string
        default: 'README.md'

jobs:
  trailhead-stats:
    name: Trailhead Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Trailhead stats
        id: trailhead-stats
        uses: nabondance/Trailhead-Stats@main
        with:
          trailhead-username: ${{ github.event.inputs.trailhead-username }}
          display-type: ${{ github.event.inputs.display-type }}
          display-file: ${{ github.event.inputs.display-file }}
